#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
EXPOSE 11769
ENV ASPNETCORE_URLS http://*:11769
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /src
COPY . .
RUN dotnet restore "./Api.Reservation.sln"
RUN dotnet build "Api.Reservation.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Api.Reservation.sln" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api.Reservation.dll"]